### ISSUE TITLE
import with -A option does not process any files

### ISSUE THREAD

**Issue by timvogtforgerock** [rockcarver/frodo#85] opened 2022-03-15 00:55 UTC
**Describe the bug**
-A option for import does not process any files

**To Reproduce**
1. Export a journey, set of journeys or all journeys using the -A option.
2. Switch to the directory containing the journey .json files3. 
3. Run frodo journey import -A

**Expected behavior**
Command imports all journey in current directory.

**Actual behaviour**
Command succeeds, but no journeys are imported.

**Screenshots**

`frodo journey import -n -A $url/am alpha $u "$p"`
`ForgeRock Identity Cloud detected.`
`Connected to ForgeRock Access Management 7.2.0-2021-14-SNAPSHOT Build d3a206af06f9a22baec020cc5dbf989f0b523dcb (2022-March-07 17:41)`
`Saving creds in /Users/<$u>/.frodo/.frodorc...`
`Updating existing connection profile <$url>/am`
`Importing all journeys from separate files...`
`done.`

**Desktop (please complete the following information):**
 - OS: MacOS
  - Version 11.6.2

**Comment by vscheuber** [comment] 2022-03-15 01:12
Thank you for the report, @timvogtforgerock ! This is a gap we haven't quite filled, yet. I'll try to get to it asap!

**Comment by vscheuber** [comment] 2022-03-15 01:14
This is also a duplicate of #31 . What should work for you, is to use 'frodo journey importAll' for the time being.

**Closed** 2022-03-15 05:47 UTC
Labels: bug
